name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Load cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Typecheck
        run: yarn typecheck

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: "Save build"
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: run-behind
          path: dist/run-behind
